apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yp36zhmy7-go
  janus-idp.io/tekton: yp36zhmy7-go
  backstage.io/kubernetes-id: yp36zhmy7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yp36zhmy7-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
